rm -vf `find . -name "*~"`
rm -vf `find . -name ".#*"`
rm -vf `find . -name "*.o"`
rm -vf `find . -name "*.pyo"`
rm -vf `find . -name "*.pyc"`
#rm -vf `find . -name "*.log"`
rm -vf `find . -name "*.out"`
rm -fv `find . -name ".DS_Store"`
rm -fv `find . -name "svn-commit.tmp"`
rm -fv `find . -name ".emanlog"`
